# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '15.0.0.dev110+g3af33bc01.d20231121'
__version_tuple__ = version_tuple = (15, 0, 0, 'dev110', 'g3af33bc01.d20231121')
